# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: AWS CICD

on: push

env:  
      AWS_REGION : "us-east-1" #Change to reflect your Region

permissions:
      id-token: write
      contents: read
      packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::313549093990:role/GithubAction_CICDRole #change to reflect your IAM role’s ARN
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      # Hello from AWS: WhoAmI
      - name: Sts GetCallerIdentity
        run: |
          aws sts get-caller-identity

      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21' # optional
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file


      - name: Build with Maven
        run: mvn clean package 
  
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          